### PR TITLE
Include missing header files

### PR DESCRIPTION
**Pull request by kashav**
Attempting to install the package before resulted in build failing with the following error:

```
$ npm install --save native-is-elevated

$ native-is-elevated@0.1.1 install path/to/project/node_modules/native-is-elevated
$ node-gyp rebuild
...
  CXX(target) Release/obj.target/is-elevated/src/is-elevated.o
../src/is-elevated.cc:37:21: error: use of undeclared identifier 'geteuid'
      bIsElevated = geteuid() == 0;
                    ^
1 error generated.
make: *** [Release/obj.target/is-elevated/src/is-elevated.o] Error 1
...
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

To test changes:
```
$ npm install --save kshvmdn/native-is-elevated#fix/undeclared-geteuid
```

### CODE REVIEW

**Comment by arkon** [comment]
What OS was this in?

**Comment by kashav** [comment]
This was on macOS 10.11.6, [broken again 😉](https://github.com/arkon/native-is-elevated/commit/81b06496ba16986460cb38d4253ff394582eee4b).

**Comment by arkon** [comment]
Wait, this works fine on my machine...

**Comment by kashav** [comment]
Could it be that I'm missing some prerequisite?

**Comment by arkon** [comment]
@kshvmdn Not sure, maybe Clang is doing some weird stuff in 10.12.x? Could you try the latest upstream commit to see if that works?

**Comment by kashav** [comment]
@arkon Yup, seems to be working! 👍

**Comment by arkon** [comment]
Sweet, thanks for helping!

**Pull request merged**
